name: virtual_ti
description: A web-based TI graphing calculator emulator.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.0